name: manga_ai
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - openai
      - flask
      - flask-cors
      - python-dotenv
      - pillow
  - numpy
  - pillow
  - pytorch
  - torchvision
  - matplotlib
  - jupyter
  - transformers
  - diffusers
  - accelerate
  - safetensors
  - gradio
  - python-dotenv 